### ISSUE TITLE
请问这个模版的兼容性怎么样？

### ISSUE THREAD

**Issue by peachapp** [zhoukaiyue/vue2-h5-tmp#1]

**Comment by zhoukaiyue** [comment]
这个模板已经在多个主流移动端浏览器上进行了测试，并且能够正常运行。同时，它也已经成功地应用于多个项目中。

**Comment by peachapp** [comment]
哦哦，封装的挺好的，就是我现在遇到一个问题，我搜了我的代码里已经没有/vue2/h5/了，但是打包之后assets中的文件都变成404了，前面多了/vue2/h5/
<img width="603" alt="image" src="https://github.com/zhoukaiyue/vue2-h5-tmp/assets/26792399/35460325-bfba-4bcb-9eba-35d0c001d08e">

**Comment by zhoukaiyue** [comment]
你好，删除 node_modules/.cache 这个目录，再试试呢？




周凯
***@***.***

13649259704


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhoukaiyue/vue2-h5-tmp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月11日(星期四) 晚上10:40
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [zhoukaiyue/vue2-h5-tmp] 请问这个模版的兼容性怎么样？ (Issue #1)





 
哦哦，封装的挺好的，就是我现在遇到一个问题，我搜了我的代码里已经没有/vue2/h5/了，但是打包之后assets中的文件都变成404了，前面多了/vue2/h5/
 image.png (view on web)
